version: '3.8'

services:
  panamax-mirror:
    image: ghcr.io/sokyrko/panamax-docker:latest
    container_name: panamax-mirror
    volumes:
      - panamax_data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  panamax_data: