[supervisord]
nodaemon=true
stopasgroup=true
killasgroup=true

[program:panamax-serve]
command=panamax serve /data
directory=/data
autostart=true
autorestart=false
exitcodes=0,2
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:cron]
command=/usr/sbin/cron -f
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0